### ISSUE TITLE
[BUG] Rename all "Country Reports" to be "Country Profiles"

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#105]
## Description
According to ask by Gates, what we're currently calling "Country Reports" should be called "Country Profiles".

## Tasks

- [x] Rename all backend items e.g models, controllers, directory names
- [x] Rename all frontend items
- [x] Fix all documentation
