### ISSUE TITLE
[PROFILES] Implement the Section Topics buttons

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#109]
## Description
Create the topic section buttons

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/41809720-f4c71b7c-76fa-11e8-816c-8bc9da2932cf.png)

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Use Flexbox to align topic divs
- [ ] Add icon selection to topics model
- [ ] Forloop sections in Django Template
