### ISSUE TITLE
[ABOUT] Add partner logos / section

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#111]
## Description
Add the partner logos / section for the about page. This will be re-used in the contact us and data services pages so should be made as a re-usable section.

## Screenshots

<img width="722" alt="screen shot 2018-06-24 at 15 43 51" src="https://user-images.githubusercontent.com/877919/41819240-a97b7674-77c5-11e8-885b-c071fb795748.png">

## Files

- ?

## Tasks

- [x] Create the section
- [x] Include section in the about page
- [x] Include section in the contact us page
