### ISSUE TITLE
[FEATURE] Implement Translation

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/Takwimu#114]
## Description
A key feature of Takwimu is that it shall be accessible in 4 core languages - English, French, Kiswahili, and Amharic. We should therefore figure out translation for content being published on the platform.

This will need to take advantage of Django's translation feature.

## Screenshots

?

## Files

- ?

## Tasks

- [x] Scope out how translation will work on the frontend
- [x] Implement translation for CMS (Backend)
- [x] Implement translation on Frontend
