### ISSUE TITLE
Contact Us (Zendesk) integration

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#12]
## Description
This is the help desk or support feature to allow end-users to ask for assistance with platform navigation, content clarification, or other information. Because there are amazingly robust services built to achieve the already, we would integrate with products such as Zendesk or ~~Intercom~~

With the support staff as our first line of interaction with customers, there are a couple of scenarios detailed [here](https://www.formilla.com/blog/customer-service-scenarios/#y) and their appropriate responses.

## Screenshots
<img width="1678" alt="screen shot 2018-05-14 at 11 46 22" src="https://user-images.githubusercontent.com/13383422/39987293-03c1f5dc-576d-11e8-9247-8c466f151e3d.png">

## Files
- [Zendesk](https://www.zendesk.com/chat/)
- [~~Intercom~~](https://www.intercom.com/live-chat)

## Tasks
- [x] Narrow down a provider to use -> Zendesk
- [ ] Integrate choosen provider into the platform
- [ ] Test the solution
