### ISSUE TITLE
[SECTIONS] Add a testimonial section

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#147]
## Description
Add a testimonial section aligned with [new designs](https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b3f9787c05dddb84bacd1de).

## Screenshots
<img width="738" alt="screen shot 2018-07-07 at 14 42 33" src="https://user-images.githubusercontent.com/877919/42410723-33db522c-81f7-11e8-88ba-0ca5079d3859.png">

## Files
- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b3f9787c05dddb84bacd1de

## Tasks

- [x] Add HTML section 
- [x] Add Admin model to allow edit via CMS
- [x] Connect Admin model with frontend
