### ISSUE TITLE
[SECTIONS] Add FAQ section

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#148]
## Description
Add FAQ section according to new designs.

## Screenshots
<img width="735" alt="screen shot 2018-07-07 at 14 42 43" src="https://user-images.githubusercontent.com/877919/42410744-9e8b714c-81f7-11e8-9f21-e1b3c66f0068.png">

## Files

- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b3f9787c05dddb84bacd1de

## Tasks

- [x] Add HTML section
- [x] Add Admin model for FAQ
- [ ] Connect Admin model with FAQ section
