### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#15]
## Description

Continuous integration will be key yo keeping our code clean and PR reviews quick. We'll even be able to deploy straight from CI. We should therefore integrate [Travis CI](https://travis-ci.com) for these purposes.

## Tasks

Tests to include for this:

- [x] [Unit tests](https://www.atlassian.com/continuous-delivery/continuous-integration-intro)
- [x] [API tests](https://www.atlassian.com/continuous-delivery/continuous-integration-intro)
- [x] [Functional tests: Homepage + Country profile pages test](https://www.atlassian.com/continuous-delivery/continuous-integration-intro)
- [ ] Code standard tests: PEP 8 test + lint
- [ ] Performance tests

**Comment by DavidLemayian** [comment]
Not exactly working unfortunately.

**Comment by phillipahereza** [comment]
@DavidLemayian https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

**Comment by DavidLemayian** [comment]
@phillipahereza What am I supposed to look at there?

**Comment by phillipahereza** [comment]
@DavidLemayian we have to wait for the travis team to migrate Takwimu from travis-ci.org to travis-ci.com. Right now we're stuck with travis-ci.org

**Comment by DavidLemayian** [comment]
@phillipahereza That's fine.
