### ISSUE TITLE
[SECTIONS] Improve support services section

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#150]
## Description
We have new designs to improve the support services section.

## Screenshots
Normal:
<img width="728" alt="screen shot 2018-07-07 at 15 13 26" src="https://user-images.githubusercontent.com/877919/42410831-55986416-81f9-11e8-9433-6bcab814c7e9.png">

Interaction:
<img width="745" alt="screen shot 2018-07-07 at 15 11 49" src="https://user-images.githubusercontent.com/877919/42410827-4b7f3ac2-81f9-11e8-8c23-ee896d8ba632.png">

## Files

- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b3f5f0717fd5e94a2aab9a3

## Tasks

- [x] Create dump of support services model examples (update documentation to load this)
- [x] Improve HTML / templates according to new designs
- [x] Introduce border right during normal view

**Comment by mtuchi** [comment]
@DavidLemayian 
What is pending on this issue ?

**Comment by DavidLemayian** [comment]
@mtuchi I think the border is lighter. Could you check with Zeplin designs to send through a hotfix? Thanks.
