### ISSUE TITLE
[SECTIONS] Improve Support Services button section

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#152]
## Description
We have new designs to improve the support services button section.

Related: #150 

## Screenshots
Regular:
<img width="737" alt="screen shot 2018-07-07 at 14 43 12" src="https://user-images.githubusercontent.com/877919/42410949-8f7e0904-81fb-11e8-933d-e569ab20ab57.png">

Interaction:
<img width="741" alt="screen shot 2018-07-07 at 15 11 15" src="https://user-images.githubusercontent.com/877919/42410952-96fa1c0e-81fb-11e8-8e12-ab6956832f9f.png">

## Files
- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b3f5f0717fd5e94a2aab9a3
- https://github.com/TakwimuAfrica/TAKWIMU/blob/5f087e747ea52dc82f057cb7ed40fa4594507cda/takwimu/templates/takwimu/_includes/sections/support-services.html

## Tasks

- [x] Introduce `_includes/sections/support-services` folder.
- [x] Move `_includes/sections/support-services.html` to `_includes/sections/support-services/button.html`.
- [x] Move `_includes/sections/priority/*.html` to `_includes/sections/support-services/*`.
- [ ] Improve look and feel according to designs.
