### ISSUE TITLE
[SECTIONS] Add How It Works section

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#154]
## Description
We have designs for how it works section.

## Screenshots
Regular:
<img width="745" alt="screen shot 2018-07-07 at 15 13 10" src="https://user-images.githubusercontent.com/877919/42411064-e22bd896-81fd-11e8-978a-dfe09230a94e.png">

Interaction:
<img width="755" alt="screen shot 2018-07-07 at 15 12 05" src="https://user-images.githubusercontent.com/877919/42411078-595cd38e-81fe-11e8-9e2b-0b99deff7273.png">

## Files
- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b3f5f006a9628231aa2da7c

## Tasks

- [x] Create CMS editing interface for How It Works
- [x] Create development / example dump data .
- [x] Create HTML/template section
- [x] Integrate backend
- [x] Add to homepage
