### ISSUE TITLE
[PROFILES] Improve profile hero

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#168]
## Description
We have new designs.

## Screenshots
<img width="1092" alt="screen shot 2018-07-10 at 01 35 35" src="https://user-images.githubusercontent.com/877919/42480100-6b5fb348-83e4-11e8-8eba-c20c2e74bbc4.png">

## Files
- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b435f81cf2739b55d0ec56c

## Tasks

- [x] Introduce background image + tint
- [x] Update country selector
- [x] Update TOC button design + make sticky
