### ISSUE TITLE
Add Community Forums

### ISSUE THREAD

**Issue by yazminjumaali** [TakwimuAfrica/TAKWIMU#17]
## Description
Part of the process with TAKWIMU is building an active community and a forum could offer a space to engage constructively with it (community) and it with itself. We should therefore look at a way of adding forum functionality. Our current options include:

1. A Django app/module that already does this but with that is at par with or better than - https://djangopackages.org/grids/g/forums/;
2. [Discourse](https://www.discourse.org) - the gold standard in self-hosted forum software.
3. [Zendesk Guide's Community feature](https://www.zendesk.com/guide/features/community-software/) - because we'll already have most our user on Zendesk for support, combined with the documentation, this offers a promising place.

## Tasks
- [ ] Research Django options for forums
- [ ] Get approval on suggested direction
- [ ] Add community forum

**Comment by mtuchi** [comment]
@yazminjumaali 
You can assign labels as wel like in trello board :smile:

**Comment by DavidLemayian** [comment]
Because we'll already be using Zendesk this will be achieved using #12
