### ISSUE TITLE
[PAGE] Create profiles/HURUmap index page

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#189]
## Description

We currently don't have `/profiles` page. It's currently using the homepage template which would be unexpected by the user.

## Screenshots
Currently, the page looks like 
![screencapture-localhost-8000-2018-07-16-10_28_24](https://user-images.githubusercontent.com/13383422/42746965-fcb65344-88e2-11e8-9655-1e13c4dc2eb7.png)
 but should look like this
![01b - country landing page](https://user-images.githubusercontent.com/13383422/42747059-60fdd23c-88e3-11e8-8244-ac50394383ba.png)

## Files
- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b438be432fbb5915d035565

## Tasks
- [x] Route the HURUmap homepage view to `/profiles`
- [x] Create template page
- [x] Style according to designs.
