### ISSUE TITLE
Create takwimu homepage template

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#19]
## Description
Create takwimu homepage template

## Tasks
- [x] Header section => Main logo and search bar section
- [x] Map section => Map section with + a call to action modal at the center of the map
- [x] Menu stick bar =>  Sticky menu navbar 
- [x] Features Section =>  Features | Services,Data and Community section
- [x] Story Section => Story divider and three feature stories 
- [x] Partners Section => Section for partners logos
- [x] Footer => Create section containing a footer blurb and  partner's logo section

**Comment by mtuchi** [comment]
@nerdlet 
what is pending in menu stick bar ?

**Comment by nerdlet** [comment]
@mtuchi  The links need to have a hover effect and link to their respective pages
