### ISSUE TITLE
[HURUmap] Publish 3 country profiles

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#192]
## Description
Publish the 3 country profiles using HURUmap

## Files
https://github.com/TakwimuAfrica/TAKWIMU/tree/develop/takwimu/templates/profile
https://github.com/TakwimuAfrica/TAKWIMU/blob/develop/takwimu/settings.py
https://github.com/TakwimuAfrica/TAKWIMU/tree/develop/takwimu/profiles

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Add necessary settings 
- [ ] Import Data into the DB
- [ ] Create Profile functions for the data
- [ ] To avoid any unnecessary conflicts, change `profiles/continent-1` url to `data/continent-1`
- [ ] Publish data to the template

**Comment by DavidLemayian** [comment]
@phillipahereza Is the conflict really likely to happen? Also, what is it like from the user perspective? Does staying on `profiles` offer a better experience or does switching to `data` make more sense? Also how does this conflict with Wazimap's use of `data/` url already set? cc @kilemensi

**Comment by kilemensi** [comment]
Isn't this already done @phillipahereza?

**Comment by phillipahereza** [comment]
@kilemensi yes it's already done, was flagging you to close it

**Comment by kilemensi** [comment]
Implemented piecewise in various PRs such as #198 , #244 , #246, etc.
