### ISSUE TITLE
[HOMEPAGE] Improve feature box styling on homepage

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#208]
## Description
Several styling inconsistencies in the feature box on the homepage:

## Screenshots
<img width="960" alt="screen shot 2018-07-21 at 23 39 31" src="https://user-images.githubusercontent.com/4629781/43040595-10ce731e-8d40-11e8-8750-53e1f6aa3da2.png">

### Tasks

- [x] Improve background colour (might need site wide update of `info` colour 
- [x] Improve 'New Country' font too big and too weight is slightly too heavy
- [x] Country flag should be desaturated
- [x] Improve button height
- [x] Update Button arrow
- [x] Use pager dots
