### ISSUE TITLE
[BUG] Improve Navbar design + structure

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#209]
## Description
Improve navbar along designs.

## Screenshots
<img width="1373" alt="screen shot 2018-07-21 at 23 46 55" src="https://user-images.githubusercontent.com/4629781/43040626-bbf709b8-8d40-11e8-850d-c4f187e44450.png">

## Tasks
- [x] Remove data menu option
- [x] Rename "Support Services" to "Our Services"
- [x] Add "Contact Us" link
- [ ] Improve font size + font weight - too big and heavy
