### ISSUE TITLE
Dockerize TAKWIMU

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#21]
## Description
To improve development and deployment, we should add a Docker workflow.

## Tasks

- [x] Add Dockerfile
- [ ] Create DockerHub organisation + repo
- [x] Add docker-compose.yml
- [ ] Create Make file similar to https://github.com/CodeForAfrica/openAFRICA

**Comment by phillipahereza** [comment]
@DavidLemayian do we need a makefile and push to dockerhub, if this is just for development and not deployment?

**Comment by DavidLemayian** [comment]
@phillipahereza Makefile is for ease of doing the push to docker hub.

**Comment by DavidLemayian** [comment]
@phillipahereza This is my favourite approach - https://github.com/alephdata/aleph/blob/master/Makefile
