### ISSUE TITLE
[BUG] Improve "Icon bar" design

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#210]
## Description
Improve "icon bar" (topics + services tab navigation) to closer to design

## Screenshots
<img width="1274" alt="screen shot 2018-07-21 at 23 50 33" src="https://user-images.githubusercontent.com/4629781/43040653-3b7a24c2-8d41-11e8-897a-8fb7dd88d0a4.png">

## Tasks
- [ ] Introduce shared tab nav styling for topics + services tabs
- [x] Improve height to be same off Zeplin
- [x] Improve Vertical divider lines - should not be full white
- [x] Improve spacing above the icons - Not enough
- [x] Improve Font weight - is a tad too heavy
