### ISSUE TITLE
[BUG] Improve updates section design

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#212]
## Description
Improve the updates section following Zeplin designs.

## Screenshots

<img width="1381" alt="screen shot 2018-07-21 at 23 59 09" src="https://user-images.githubusercontent.com/4629781/43040702-8f8e3c96-8d42-11e8-9efa-f832f85cb56c.png">

## Tasks

- [x] Remove strange padding at the top and bottom
- [x] Improve Font weight for the descriptor text - is too heavy
- [x] Introduced separating dashed line
