### ISSUE TITLE
[BUG] Improve support services button design

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#213]
## Description
Improve support / data services button to match designs.

## Screenshots
<img width="961" alt="screen shot 2018-07-22 at 00 03 36" src="https://user-images.githubusercontent.com/4629781/43040719-ffb50d92-8d42-11e8-9efd-421fee574f03.png">

## Tasks
- [x] Height needs to be increased to match design
- [x] First line should not be full white
- [x] Font weight is a tad too heavy for the linked CTA text
