### ISSUE TITLE
[BUG] Improve Country explorer tool styling

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/Takwimu#214]
## Description
Improve country explorer section design

## Screenshots
<img width="1775" alt="screen shot 2018-07-22 at 00 07 52" src="https://user-images.githubusercontent.com/4629781/43040737-a29d2fbc-8d43-11e8-91f6-5c30a19f8afa.png">

## Tasks
- [ ] Increase Flag icons size - are smaller than designed
- [ ] Increase Horizontal spacing between elements - is a lot tighter than designed
- [X] [`wont fix`] ~~Should the flags not be greyscale as originally requested? I don't mind eitherway~~

- [ ] Vertical divider lines extend too far above & below the flags:
  - [ ] Reduce `padding-top` of top 5 country flags
  - [ ] Reduce `padding-bottom` of bottom 5 country flags
