### ISSUE TITLE
[BUG] Improve FAQ section styling

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#215]
## Description
Improve FAQ section styling

### Fix 1
<img width="1799" alt="screen shot 2018-07-22 at 00 10 56" src="https://user-images.githubusercontent.com/4629781/43040769-546dff46-8d44-11e8-870f-180e977a35e8.png">

### Fix 2
<img width="1674" alt="screen shot 2018-07-22 at 00 15 08" src="https://user-images.githubusercontent.com/4629781/43040770-589a92f0-8d44-11e8-991f-4fddd113c2dc.png">

## Tasks
- [x] Wrap content around `container` class (see red lines on screenshot [Fix 1])
- [x] Answer title should be full black and slightly smaller to match design
- [x] Answer body text weight needs to be reduced to match design
- [x] button height, label font size & weight to match design
