### ISSUE TITLE
[BUG] Improve footer styling

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#216]
## Description
Improve footer styling according to Zeplin designs.

## Screenshots
<img width="1356" alt="screen shot 2018-07-22 at 00 18 26" src="https://user-images.githubusercontent.com/4629781/43040797-137ab29e-8d45-11e8-9b83-be2a7dccd452.png">

## Tasks
- [x] All logos should be white out. AP logo is currently 2 tone (white & grey) (check brand templates Google Drive folders for these)
- [x] width of logo boxes need to be increased
- [x] Bottom bar in footer needs to have height increased
- [x] Social media logos, separators and colour should match design
