### ISSUE TITLE
[BUG] Improve country profile hero styling

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#217]
## Description
Improve profile hero design

## Screenshots
<img width="1510" alt="screen shot 2018-07-22 at 00 23 29" src="https://user-images.githubusercontent.com/4629781/43040824-2631e6b8-8d46-11e8-94dd-1ad47e77b030.png">

## Tasks

- [x] Crumb trail font a little too big & incorrect separator being used - should use: &raquo;
- [x] Country flag has inner blue border
- [x] Section title font e.g., "Country Profile" is too big
- [x] Profile download button does not match
- [x] Table of contents label too big
- [x] Table of contents icon doesn't match
- [x] Table of contents button height needs increasing
