### ISSUE TITLE
[PROFILE] Improve country profile topics

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/Takwimu#218]
## Description
Improve the profile topic design to be closer to the designs.

## Screenshots
<img width="1279" alt="screen shot 2018-07-22 at 00 30 03" src="https://user-images.githubusercontent.com/4629781/43040842-8ab30e1e-8d46-11e8-9bd1-a0de323eb526.png">

## Tasks

- [x] Left hand menu is a little more narrow than designed. Not too much of an issue as I realise you're probably working to different widths
- [x] Left hand menu items font weight needs to come down a bit when inactive.
- [x] Active items on left hand menu needs a higher font weight
- [x] The body font is too heavy and needs to be brought down to match design
- [x] None of the icons used match design
- [x] Buttons under data visuals missing that allow user to navigate without the LHS menu
- [x] If possible, it would be good to allow the LHS menu to follow the user down the scroll for that section to the point where the next section becomes visible or if the screen height is insufficient to allow all items to be displayed

**Comment by mtuchi** [comment]
**Buttons under data visuals missing that allow user to navigate without the LHS menu** 
Will be fixed with #394

**Comment by mtuchi** [comment]
**If possible, it would be good to allow the LHS menu to follow the user down the scroll for that section to the point where the next section becomes visible or if the screen height is insufficient to allow all items to be displayed**

**Note:** At the moment this can be achieved using sticky-top, but this feature has browser support limitation, so should be looked again in the near future

**Comment by DavidLemayian** [comment]
@mtuchi Please use sticky-top for the nav. Thanks.
