### ISSUE TITLE
Integrate HURUmap

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#22]
## Description
Include the [CodeForAfricaLabs/HURUmap](https://github.com/CodeForAfricaLabs/HURUmap) package into TAKWIMU.

## Tasks

- [ ] Add HURUmap to requirements.txt
- [ ] Provide easy way to work with local development version
- [ ] Tweak any settings as necessary
