### ISSUE TITLE
[BUG] Fix Profile TOC

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#221]
## Description
Don't mind some of your styling changes on this menu, but could you please update the following:

## Screenshots
<img width="898" alt="screen shot 2018-07-22 at 00 49 33" src="https://user-images.githubusercontent.com/4629781/43040925-e4188a1c-8d49-11e8-8204-6e4563dac019.png">

## Tasks

- [x] Color and size of Nigerian flag to match design
- [x] Color of country drop down should not be that blue.
- [x]  Please increase font weight of section titles (and reduce the font weight of the sub-section links)
- [x]  Please update the + and – icons to match the design
- [x]  Please collapse all accordions by default (bar the first section - this is to indicate behaviour to the user.

**Comment by mtuchi** [comment]
@DavidLemayian these two task am not sure if i completely understand
- [ ] Color and size of Nigerian flag to match design
- [ ] Color of country drop down should not be that blue.
 can you shade more light ?

**Comment by seangp** [comment]
Hi @mtuchi 

1. The flag image currently being used in the build is different in size and colour to the one in the design. I believe the design flag is 52px X 52px (https://zpl.io/V0yQ5GR). It actually looks fine as it is, so don't worry about changing it.

2. The country label for dropdown is now correct on the dev site so you can mark that task as done.

**Comment by DavidLemayian** [comment]
@mtuchi ☝️

**Comment by mtuchi** [comment]
@DavidLemayian what is pending on this issue ?
