### ISSUE TITLE
Improve design of Support Services Page

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#265]
**Description**
Improve support services page according to designs.

**Files**
Web: https://zpl.io/bAqJwpq
App: zpl://screen?sid=5b43e70b9811ea0502dce4b5&pid=5b1a4192c1a8233544fcc66a

**Screenshots**
<img width="735" alt="screen shot 2018-08-07 at 13 59 30" src="https://user-images.githubusercontent.com/877919/43775090-1fa5490a-9a54-11e8-9b6b-d5d0dcde443d.png">

**Tasks**
- [x] Horizontally align all services like in zeplin design
- [x] A consistency height and width for the image
- [x] Same height for each services

**Comment by seangp** [comment]
@africapractice @kilemensi @phillipahereza I have provided a new design for this page: https://zpl.io/bAqJwpq

**Comment by DavidLemayian** [comment]
Screenshot of Zeplin:

<img width="741" alt="screen shot 2018-07-30 at 15 39 19" src="https://user-images.githubusercontent.com/877919/43397867-ed15a7a0-940e-11e8-88a7-d12865a0abf2.png">

**Comment by DavidLemayian** [comment]
@africapractice Notice you asked for another tweak on Slack. Will wait until signed-off on here and we'll plan for it.

**Comment by mtuchi** [comment]
@DavidLemayian 
Can i get clarity on the task for this issue ?
