### ISSUE TITLE
[NAVBAR] Improve About Navbar look and feel

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#290]
**Describe the bug**
The About Navbar dropdown can be improved aligned with designs.

**Expected look**
<img width="721" alt="screen shot 2018-07-31 at 17 29 49" src="https://user-images.githubusercontent.com/877919/43466064-5bb2b508-94e7-11e8-804a-b93acd0da7de.png">

**Screenshots**
![screen shot 2018-07-31 at 17 26 29](https://user-images.githubusercontent.com/877919/43466000-4131a66c-94e7-11e8-9686-700d4edf56dd.png)

**Tasks**
- [ ] All dropdowns:
  - [x] Left-align the dropdown title + description
    - [x] Make description font-weight-light
  - [x] Link color: `#7ab1f2`
  - [ ] Line height `2.4`

- [x] Change "Support Services" to "Our Data Services"
- [x] Add "Insights & Stories" pointing to Medium.
- [x] Follow us:
  - [x] Center align
  - [x] Border opacity - `opacity: 0.2;`
- [x] Partner logos:
  - [x] Fix AP logo to be white
  - [x] Should be in the same column as "Follow Us"
  - [x] Change "Takwimu is an initiative by" to "An initiative by" while using the "Follow us" font-weight.

**Comment by nerdlet** [comment]
@DavidLemayian A line height of 2.4 for the description is a bit large given the font size and weight in use, instead I reduced it to 1.8
