### ISSUE TITLE
[HURUmap] Add SDG Data

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#293]
**Is your feature request related to a problem? Please describe.**
Agreed early on, we'd want to add Disaggregated SDG Data.

**Describe the solution you'd like**
A way to navigate data we according to SDGs.

**Describe alternatives you've considered**
Designs:
Web: https://zpl.io/VKqZMkP
App: zpl://screen?sid=5b438c02d51487cc5f85b08f&pid=5b1a4192c1a8233544fcc66a

We could create a HURUmap profile (similar to census one) that "clusters" FieldTables already available on the platform according to SDGs. This "SDG profile" would then have colour code in each section for each SDG.

**Additional context**
Linked to #292 , #291,  #294 

**Tasks**
Proposed steps:
- [ ] Create a static store (in code as constants?) for SDGs because DB / CMS not need
- [ ] Create HURUmap profile for this
- [ ] Create template for the HURUmap profile with the "categorisation"
- [ ] ?

**Comment by phillipahereza** [comment]
@kilemensi do we hope to go sub national with this data? cc @DavidLemayian

**Comment by kilemensi** [comment]
Since we're doing this on **HURUmap**, I would think so @phillipahereza.
