### ISSUE TITLE
[HOMEPAGE] Improve Carousel

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#301]
## Description
Improve carousel look, feel, and build with the tasks (below).

## Screenshots

**Current:**
<img width="372" alt="screen shot 2018-08-01 at 12 45 07" src="https://user-images.githubusercontent.com/877919/43518070-7d00ee6c-9593-11e8-9f26-43d2e9449d19.png">

**Designs:**
<img width="209" alt="screen shot 2018-08-01 at 09 47 40" src="https://user-images.githubusercontent.com/877919/43518081-8461e01c-9593-11e8-8d11-0347ff61932d.png">

## Files
Designs:
Web: https://zpl.io/blp4EPX
App: zpl://screen?sid=5b608933e994b9ea7b391b9d&pid=5b1a4192c1a8233544fcc66a

## Tasks

- [x] Create folder `takwimu/templates/_includes/homepage/carousel/`
- [x] Move `hero_detail.html` + `beta_detail.html` to created folder above (`carousel/`)
- [x] Rework such that `hero_detail.html` and `beta_detail.html` work from single `carousel/item_detail.html`
