### ISSUE TITLE
[SEARCH] Implement search filter 

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/Takwimu#331]
## Description

Add a search filter on the sidebar of the search results.

## Screenshots
![filter](https://user-images.githubusercontent.com/6592749/44400755-00431680-a555-11e8-8139-8e1398db4439.png)

![side](https://user-images.githubusercontent.com/6592749/45084756-bdae3c00-b107-11e8-9ac0-bb78194fd3ce.png)

## Files

[Zeplin Designs](https://zpl.io/brEmod7)

## Tasks
The highlighted task should follow the design layout provide on zeplin :arrow_up_small: 
- [x] Closable popover
- [x] Create closable tags 
- [x] Filter by country 
- [x] Create filter by keyword input box
- [x] Filter by SDG indicators
- [x] Filter by topics
- [x] Popover for multiple  select items
