### ISSUE TITLE
[SEARCH] Implement the search result page

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/TAKWIMU#333]
## Description

Design the result page that will contain all search results by data.

## Screenshots
![screenshot_2018-09-05_12-21-25](https://user-images.githubusercontent.com/6592749/45084194-6491d880-b106-11e8-9586-54f4cf29325d.png)

## Files
[Zeplin design](https://zpl.io/bLDBL67)

## Tasks
Use the zeplin design file provided above :arrow_up: 
- [x] Search result title with results hit counter
- [x] Search result table 
- [x] Style according to zeplin 

## Related Issues
#332 #331
