### ISSUE TITLE
[SEARCH] Implement expandable result item

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/TAKWIMU#334]
## Description
The user should be able to collapse a select item and collapse the item with easy. 
Also the user should be able to expand all result at once for easy comparison and collapse all result at once.

## Screenshots
![screenshot_2018-09-05_12-26-01](https://user-images.githubusercontent.com/6592749/45084397-e550d480-b106-11e8-9111-1eda96a936dc.png)
#### Hurumap data in search 
![screenshot_2018-09-05_12-29-38](https://user-images.githubusercontent.com/6592749/45084619-7162fc00-b107-11e8-978c-4f4997e7c9dc.png)

## Files
[Zeplin Design](https://zpl.io/am418L6) 

## Tasks

- [x] Expand and collapse a selected item capability
- [x] Expand all result items 
- [x] Collapse all items

## Related Issue
#333 #332 #331 

## Additional Notes
This issue depends on #333
