### ISSUE TITLE
[FEATURE] Add pagination on search results page

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/TAKWIMU#335]
## Description

Search results pagination for easy navigation between the results page.  

## Screenshots
![pagenate](https://user-images.githubusercontent.com/6592749/43956190-e2c9ee50-9cab-11e8-8750-8963681cdba9.png)

## Files
[Zeplin Design](https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b4405a75792d5de5f566922)

## Tasks

- [x] Add pagination links
- [x] Previous and next button
- [x] Result per page select box
- [x] Style according to zeplin design

## Related Issues
#334 #333 #332 #331 

## Additional Notes
This issue depends on #333

**Comment by DavidLemayian** [comment]
@mtuchi Is this implemented already? If so, please close.
