### ISSUE TITLE
Create a simple landing page

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#4]
## Description
We should create a simple landing page to collect e-mail addresses and work as a "coming soon" page.

## Screenshots
![38874399-a64fef24-4260-11e8-83cd-76d038442467](https://user-images.githubusercontent.com/877919/39001533-2ab649a8-43ff-11e8-9403-8edf8fb50d97.png)

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Create Mailchimp Account
- [ ] Create landing page on Github Pages
- [ ] Add Google Analytics
- [ ] Add links to social media
