### ISSUE TITLE
Placeholder sitemap and content

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#40]
## Description
Create default pages content for about us page, terms of use, and privacy policy.

## Files

Trello board: https://trello.com/c/Mjq7e0DQ

Google Doc: https://drive.google.com/drive/folders/1Ych0US_14tiwFip0JSc-c5_dL_l2HacY?usp=sharing
## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Create About Us page content
- [x] Create Privacy Policy page content
- [x] Create Terms of Use page content
- [ ] Create Contact page content
