### ISSUE TITLE
Implement Navbar as in Designs

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#45]
## Description
Using Twitter Bootstrap, we should implement the navbar as laid out in the Zeplin designs.

**These changes should be done against `feature/templates` branch. These are PR and new branches created.**

## Screenshots
<img width="741" alt="screen shot 2018-06-04 at 10 58 55" src="https://user-images.githubusercontent.com/877919/40905360-565d06a4-67e6-11e8-8206-996bec013eeb.png">

## Files

- Zeplin: https://app.zeplin.io/project/5ae37a224a28f19738a929fb
- Navar file: https://github.com/TakwimuAfrica/TAKWIMU/blob/feature/templates/takwimu/templates/takwimu/_includes/navbar.html

## Tasks

- [x] Create **basic** blue navbar with Bootstrap (minus the "My Collections" button)
- [x] Create secondary navbar using flex
- [x] Add login/account button
- [x] Style according to designs on Zeplin
