### ISSUE TITLE
Explore other Data Section

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#47]
Implement the `explore other data` section as laid out in the Zeplin designs.

**These changes should be done against feature/templates branch. These are PR and new branches created.**

## Screenshots
<img width="1083" alt="screen shot 2018-06-04 at 17 20 16" src="https://user-images.githubusercontent.com/13383422/40922736-9996b156-681b-11e8-8ba2-368a8717cdf5.png">

## Files
- Zeplin: https://app.zeplin.io/project/5ae37a224a28f19738a929fb
- Tablet View: https://app.zeplin.io/project/5ae37a224a28f19738a929fb/screen/5b0f61ec5a33f75539aa2998
- Mobile View: https://app.zeplin.io/project/5ae37a224a28f19738a929fb/screen/5b0f61f3c2d9875d0875ab5d

## Tasks

- [x] Create section for desktop view
- [x] Add logic to grey out current country profile flag 
- [x] Create Tablet View
- [x] Create Mobile View
- [x] Style according to Zepellin designs
