### ISSUE TITLE
Implement Fonts

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#49]
## Description
The designs have a lot of font styles. We should implement them accordingly across the site.

## Screenshots
N/A

## Files

- Zeplin: https://app.zeplin.io/project/5ae37a224a28f19738a929fb/screen/5b0f62dd44ba558c4fa33633
- Font (Roboto)

## Tasks

- [x] Add font in head before CSS
- [x] Create for the basic HTML elements e.g p, headings, body
- [x] Add to the specific classes e.g jumbotron / navbar
