### ISSUE TITLE
Pull latest stories from Medium.com

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#50]
## Description
Implement the stories section as laid out in the Zeplin designs and pull blog posts from the medium API

**These changes should be done against `feature/templates` branch. These are PR and new branches created.**

## Screenshots
<img width="722" alt="screen shot 2018-06-04 at 17 49 56" src="https://user-images.githubusercontent.com/13383422/40924364-c2682d2c-681f-11e8-9074-73b3bf3225c9.png">

### Tablet View
<img width="386" alt="screen shot 2018-06-04 at 17 51 02" src="https://user-images.githubusercontent.com/13383422/40924436-eb483516-681f-11e8-8a5e-8a515fc22c62.png">

### Mobile View
<img width="192" alt="screen shot 2018-06-04 at 17 52 18" src="https://user-images.githubusercontent.com/13383422/40924518-1927efb2-6820-11e8-9ad8-c702a781e187.png">

## Files
- Zeplin: https://app.zeplin.io/project/5ae37a224a28f19738a929fb
- Medium API: https://github.com/Medium/medium-api-docs
- Medium Python SDK: https://github.com/Medium/medium-sdk-python

## Tasks

- [x] Create section
- [x] Create tablet view
- [x] Create mobile view 
- [x] Pull stories from Medium
- [x] Style according to designs on Zeplin
