### ISSUE TITLE
[HURUmap] Implement Data Visualisation

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#58]
## Description
Implement the Country section analysis Element as laid out in the Zeplin designs.

## Screenshots
<img width="714" alt="screen shot 2018-06-15 at 18 36 02" src="https://user-images.githubusercontent.com/877919/41477251-617fee5e-70cc-11e8-9c9d-0b3245c7278f.png">

## Files
- Zeplin: https://app.zeplin.io/project/5ae37a224a28f19738a929fb

## Tasks

- [ ] Add frontend assets used by HURUmap
- [ ] Add visualisation selector to DataIndicator Inline panel
- [ ] Integrate HURUmap FieldTable w/ DataIndicator properties on backend
- [ ] Have functioning data view buttons

**Comment by mtuchi** [comment]
@phillipahereza 
Do you need help on this one ?
