### ISSUE TITLE
[PROFILES] Implement TOC Sidebar Nav

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#68]
Implement table of contents as is in the designs with the animations to show it and hide it

<img width="724" alt="screen shot 2018-06-13 at 14 39 32" src="https://user-images.githubusercontent.com/13383422/41349152-a3f80ff2-6f17-11e8-8d48-c2017873eb47.png">

### Tasks

- [ ] Have TOC button at the far right
- [ ] Create div with the absolute position + scrollable
- [ ] Populate layout with content
- [ ] Make dismissible + show on click
