### ISSUE TITLE
[SDG] Explore by sustainable development goals

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/Takwimu#70]
## Description
Implement the SDG navigator Section as laid out in the Zeplin designs. 

### Step 1
**Home Page**
<img width="719" alt="screen shot 2018-06-13 at 12 00 23" src="https://user-images.githubusercontent.com/13383422/41341106-960ba7d4-6f01-11e8-8a88-b0f121c1a452.png">

**SDG landing page**
<img width="714" alt="screen shot 2018-06-13 at 12 18 32" src="https://user-images.githubusercontent.com/13383422/41342073-01b7add2-6f04-11e8-8a3d-f2608ff52407.png">

### Step 2
**Agriculture not selected(grey) so all agriculture related SDGs are also greyed out**
<img width="721" alt="screen shot 2018-06-13 at 12 22 43" src="https://user-images.githubusercontent.com/13383422/41342368-be14f5de-6f04-11e8-8b5c-f94d9d3be542.png">

### Step 3
<img width="724" alt="screen shot 2018-06-13 at 12 24 11" src="https://user-images.githubusercontent.com/13383422/41342380-c6ba9716-6f04-11e8-9ce5-8edb3c551401.png">

## Files

- Zeplin: https://app.zeplin.io/project/5ae37a224a28f19738a929fb

## Tasks

- [x] Create the section
- [x] Add option to switch styles depending on which page this section is displayed e.g. `{% include 'takwimu/_includes/report/section_sdg_nav.html'  with page='homepage'%}` would load the homepage styles and `{% include 'takwimu/_includes/report/section_sdg_nav.html'  with page='sdg_page'%}` will show same section with SDG landing page styling
- [x] Style according to designs on Zeplin
- [x] Add animations and interactions

**Comment by mtuchi** [comment]
@phillipahereza are there mobile and tablet designs for this issue ?

**Comment by phillipahereza** [comment]
@mtuchi I think you should focus on desktop first

**Comment by phillipahereza** [comment]
@mtuchi make your PR
