### ISSUE TITLE
[Media Centre] Implement Resources and Stories Page

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/Takwimu#78]
## Description
This page should be created from the dashboard as a child of media center page
## Screenshots
<img width="363" alt="screen shot 2018-06-14 at 15 38 59" src="https://user-images.githubusercontent.com/13383422/41412580-2d709bec-6fe9-11e8-8c2e-8282db83860e.png">
<img width="364" alt="screen shot 2018-06-14 at 15 39 32" src="https://user-images.githubusercontent.com/13383422/41412581-2db51c2c-6fe9-11e8-92d4-14f8c56919c7.png">

## Tasks
- [ ] Create Page Model as a child page of media centre page
- [ ] Implement page as in the Zaang designs
- [ ] Add video player modal
