### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#8]
## Description

Being an open source project, we should create a contribution guide from the onset to help with pointing contributors to resources, process, and other policies / code of conduct that improves the entire process.

## Links

Some links we can borrow off:
- [Contributor Covenant](https://www.contributor-covenant.org)
- [Contribution Guide](http://www.contribution-guide.org)

## Tasks

- [x] Create `CONTRIBUTING.md`
- [x] Add contribution section in `README.md`
- [x] If Contributor Covenant adopted, add to [list of adopters](https://www.contributor-covenant.org/adopters)
