### ISSUE TITLE
[TOPIC] Improve data indicator nav pills

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#86]
## Description
Currently the nav pills are the standard Bootstrap ones, we should improve the look and feel to be closer to designs.

Note: Please try to use in-line CSS + `<style>` tags at bottom of topic_detail.html instead of making CSS edits in `takwimu.scss`.

## Screenshots
<img width="714" alt="screen shot 2018-06-15 at 18 36 02" src="https://user-images.githubusercontent.com/877919/41476764-29ed92bc-70cb-11e8-88d6-546c6f149282.png">

## Files
- ?

## Tasks

- [x] Add `.active` class to first data indicator (either JS or forloop counter in Django template)
- [x] Make the nav pills right colour and no round edges.
- [x] Active state should use eye instead of colour change
